name: Build Android and iOS Apps

on:
  push:
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Store build outputs
        uses: actions/upload-artifact@v4
        with:
          name: android-build-outputs
          path: composeApp/build/outputs/

  build-ios:
    runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build iOS binaries
        run: ./gradlew composeApp:iosArm64Binaries

      - name: Store iOS binaries
        uses: actions/upload-artifact@v4
        with:
          name: ios-binaries
          path: composeApp/build/bin/iosArm64
